/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTicketResponseDto
 */
export interface AddTicketResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AddTicketResponseDto
     */
    id?: number;
}

/**
 * Check if a given object implements the AddTicketResponseDto interface.
 */
export function instanceOfAddTicketResponseDto(value: object): value is AddTicketResponseDto {
    return true;
}

export function AddTicketResponseDtoFromJSON(json: any): AddTicketResponseDto {
    return AddTicketResponseDtoFromJSONTyped(json, false);
}

export function AddTicketResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTicketResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AddTicketResponseDtoToJSON(json: any): AddTicketResponseDto {
    return AddTicketResponseDtoToJSONTyped(json, false);
}

export function AddTicketResponseDtoToJSONTyped(value?: AddTicketResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

