/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstalledEnvironmentDto
 */
export interface InstalledEnvironmentDto {
    /**
     * 
     * @type {number}
     * @memberof InstalledEnvironmentDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InstalledEnvironmentDto
     */
    title?: string | null;
}

/**
 * Check if a given object implements the InstalledEnvironmentDto interface.
 */
export function instanceOfInstalledEnvironmentDto(value: object): value is InstalledEnvironmentDto {
    return true;
}

export function InstalledEnvironmentDtoFromJSON(json: any): InstalledEnvironmentDto {
    return InstalledEnvironmentDtoFromJSONTyped(json, false);
}

export function InstalledEnvironmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstalledEnvironmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function InstalledEnvironmentDtoToJSON(json: any): InstalledEnvironmentDto {
    return InstalledEnvironmentDtoToJSONTyped(json, false);
}

export function InstalledEnvironmentDtoToJSONTyped(value?: InstalledEnvironmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

