/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusDto2
 */
export interface StatusDto2 {
    /**
     * 
     * @type {number}
     * @memberof StatusDto2
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof StatusDto2
     */
    title?: string | null;
}

/**
 * Check if a given object implements the StatusDto2 interface.
 */
export function instanceOfStatusDto2(value: object): value is StatusDto2 {
    return true;
}

export function StatusDto2FromJSON(json: any): StatusDto2 {
    return StatusDto2FromJSONTyped(json, false);
}

export function StatusDto2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusDto2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function StatusDto2ToJSON(json: any): StatusDto2 {
    return StatusDto2ToJSONTyped(json, false);
}

export function StatusDto2ToJSONTyped(value?: StatusDto2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

