/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketReplyDto
 */
export interface TicketReplyDto {
    /**
     * 
     * @type {number}
     * @memberof TicketReplyDto
     */
    replyId?: number;
    /**
     * 
     * @type {number}
     * @memberof TicketReplyDto
     */
    tId?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketReplyDto
     */
    reply?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TicketReplyDto
     */
    replyDate?: Date;
}

/**
 * Check if a given object implements the TicketReplyDto interface.
 */
export function instanceOfTicketReplyDto(value: object): value is TicketReplyDto {
    return true;
}

export function TicketReplyDtoFromJSON(json: any): TicketReplyDto {
    return TicketReplyDtoFromJSONTyped(json, false);
}

export function TicketReplyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketReplyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'replyId': json['replyId'] == null ? undefined : json['replyId'],
        'tId': json['tId'] == null ? undefined : json['tId'],
        'reply': json['reply'] == null ? undefined : json['reply'],
        'replyDate': json['replyDate'] == null ? undefined : (new Date(json['replyDate'])),
    };
}

export function TicketReplyDtoToJSON(json: any): TicketReplyDto {
    return TicketReplyDtoToJSONTyped(json, false);
}

export function TicketReplyDtoToJSONTyped(value?: TicketReplyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'replyId': value['replyId'],
        'tId': value['tId'],
        'reply': value['reply'],
        'replyDate': value['replyDate'] == null ? undefined : ((value['replyDate']).toISOString()),
    };
}

