/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketRequestDto
 */
export interface TicketRequestDto {
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    applicationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    stackTrace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    device?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    browser?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    resolution?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TicketRequestDto
     */
    priorityId?: number;
    /**
     * 
     * @type {number}
     * @memberof TicketRequestDto
     */
    ticketTypeId?: number;
    /**
     * 
     * @type {number}
     * @memberof TicketRequestDto
     */
    statusId?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketRequestDto
     */
    userOID?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TicketRequestDto
     */
    installedEnvironmentId?: number;
}

/**
 * Check if a given object implements the TicketRequestDto interface.
 */
export function instanceOfTicketRequestDto(value: object): value is TicketRequestDto {
    return true;
}

export function TicketRequestDtoFromJSON(json: any): TicketRequestDto {
    return TicketRequestDtoFromJSONTyped(json, false);
}

export function TicketRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'applicationName': json['applicationName'] == null ? undefined : json['applicationName'],
        'stackTrace': json['stackTrace'] == null ? undefined : json['stackTrace'],
        'device': json['device'] == null ? undefined : json['device'],
        'browser': json['browser'] == null ? undefined : json['browser'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'priorityId': json['priorityId'] == null ? undefined : json['priorityId'],
        'ticketTypeId': json['ticketTypeId'] == null ? undefined : json['ticketTypeId'],
        'statusId': json['statusId'] == null ? undefined : json['statusId'],
        'userOID': json['userOID'] == null ? undefined : json['userOID'],
        'installedEnvironmentId': json['installedEnvironmentId'] == null ? undefined : json['installedEnvironmentId'],
    };
}

export function TicketRequestDtoToJSON(json: any): TicketRequestDto {
    return TicketRequestDtoToJSONTyped(json, false);
}

export function TicketRequestDtoToJSONTyped(value?: TicketRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'url': value['url'],
        'applicationName': value['applicationName'],
        'stackTrace': value['stackTrace'],
        'device': value['device'],
        'browser': value['browser'],
        'resolution': value['resolution'],
        'priorityId': value['priorityId'],
        'ticketTypeId': value['ticketTypeId'],
        'statusId': value['statusId'],
        'userOID': value['userOID'],
        'installedEnvironmentId': value['installedEnvironmentId'],
    };
}

