/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketTypeDto2
 */
export interface TicketTypeDto2 {
    /**
     * 
     * @type {number}
     * @memberof TicketTypeDto2
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketTypeDto2
     */
    title?: string | null;
}

/**
 * Check if a given object implements the TicketTypeDto2 interface.
 */
export function instanceOfTicketTypeDto2(value: object): value is TicketTypeDto2 {
    return true;
}

export function TicketTypeDto2FromJSON(json: any): TicketTypeDto2 {
    return TicketTypeDto2FromJSONTyped(json, false);
}

export function TicketTypeDto2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketTypeDto2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function TicketTypeDto2ToJSON(json: any): TicketTypeDto2 {
    return TicketTypeDto2ToJSONTyped(json, false);
}

export function TicketTypeDto2ToJSONTyped(value?: TicketTypeDto2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

