/* tslint:disable */
/* eslint-disable */
/**
 * TicketTracking.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDto2
 */
export interface UserDto2 {
    /**
     * 
     * @type {string}
     * @memberof UserDto2
     */
    oid?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto2
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto2
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto2
     */
    fullName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserDto2
     */
    lastScannedUtc?: Date | null;
}

/**
 * Check if a given object implements the UserDto2 interface.
 */
export function instanceOfUserDto2(value: object): value is UserDto2 {
    return true;
}

export function UserDto2FromJSON(json: any): UserDto2 {
    return UserDto2FromJSONTyped(json, false);
}

export function UserDto2FromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto2 {
    if (json == null) {
        return json;
    }
    return {
        
        'oid': json['oid'] == null ? undefined : json['oid'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'lastScannedUtc': json['lastScannedUtc'] == null ? undefined : (new Date(json['lastScannedUtc'])),
    };
}

export function UserDto2ToJSON(json: any): UserDto2 {
    return UserDto2ToJSONTyped(json, false);
}

export function UserDto2ToJSONTyped(value?: UserDto2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oid': value['oid'],
        'displayName': value['displayName'],
        'email': value['email'],
        'fullName': value['fullName'],
        'lastScannedUtc': value['lastScannedUtc'] == null ? undefined : ((value['lastScannedUtc'] as any).toISOString()),
    };
}

